import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { Compass, AlertTriangle, ArrowRight, CheckCircle2, ChevronRight } from 'lucide-react';
import toast from 'react-hot-toast';

const Recommendation = () => {
  const { apiFetch } = useAuth();
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchRecommendations = async () => {
      try {
        const data = await apiFetch('/recommendations');
        setRecommendations(data.recommendations || []);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecommendations();
  }, []);

  if (loading) {
    return (
      <div className="flex h-[calc(100vh-4rem)] items-center justify-center">
        <div className="h-8 w-8 animate-spin rounded-full border-4 border-purple-500 border-t-transparent"></div>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-5xl px-4 py-8">
      {/* Page Header */}
      <div className="mb-8">
        <h1 className="text-2xl font-bold text-slate-800 dark:text-white flex items-center gap-2">
          <Compass className="h-6 w-6 text-purple-600" /> Career Recommendations
        </h1>
        <p className="text-sm text-slate-500 dark:text-slate-400">
          Explore your top career paths generated by our custom student profile analytics.
        </p>
      </div>

      {recommendations.length === 0 ? (
        <div className="rounded-2xl border border-slate-100 bg-white p-12 text-center shadow-sm dark:border-slate-905 dark:bg-slate-950">
          <div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-2xl bg-purple-50 text-purple-600 dark:bg-purple-950/40">
            <AlertTriangle className="h-6 w-6" />
          </div>
          <h2 className="text-lg font-bold text-slate-800 dark:text-white">Profile Analytics Pending</h2>
          <p className="mx-auto mt-2 max-w-sm text-sm text-slate-500 dark:text-slate-400">
            You need to complete your student profile details first before we can run career analysis.
          </p>
          <Link to="/profile" className="btn-primary mt-6 inline-block">Complete Profile</Link>
        </div>
      ) : (
        <div className="space-y-6">
          {recommendations.map((rec, index) => {
            // Determine badge colors based on score
            const score = rec.score;
            let gaugeColor = 'bg-purple-600';
            let bgLight = 'bg-purple-50 text-purple-700 dark:bg-purple-950/40 dark:text-purple-400';
            
            if (score >= 80) {
              gaugeColor = 'bg-purple-600';
            } else if (score >= 60) {
              gaugeColor = 'bg-indigo-500';
              bgLight = 'bg-indigo-50 text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-400';
            } else {
              gaugeColor = 'bg-slate-500';
              bgLight = 'bg-slate-100 text-slate-700 dark:bg-slate-900/60 dark:text-slate-400';
            }

            return (
              <div 
                key={rec.career_id} 
                className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm dark:border-slate-900 dark:bg-slate-950 transition-all duration-300 hover:shadow-md hover:border-purple-200/40 dark:hover:border-purple-900/20"
              >
                <div className="flex flex-col gap-6 md:flex-row md:items-start md:justify-between">
                  {/* Left: Info details */}
                  <div className="flex-1 space-y-4">
                    <div className="flex flex-wrap items-center gap-3">
                      <span className={`inline-flex items-center gap-1 rounded-full px-3 py-1 text-xs font-bold ${bgLight}`}>
                        Rank #{index + 1}
                      </span>
                      <h2 className="text-xl font-bold text-slate-800 dark:text-white">{rec.title}</h2>
                    </div>

                    <div className="space-y-2">
                      <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">Why this matches your profile:</h3>
                      <ul className="space-y-1.5">
                        {rec.reasons.map((reason, rIdx) => (
                          <li key={rIdx} className="flex items-start gap-2 text-xs text-slate-600 dark:text-slate-300">
                            <CheckCircle2 className="h-4 w-4 shrink-0 text-purple-600 mt-0.5" />
                            <span>{reason}</span>
                          </li>
                        ))}
                      </ul>
                    </div>

                    {rec.dataset_support ? (
                      <div className="rounded-2xl border border-purple-100 bg-purple-50/60 px-4 py-3 text-xs text-purple-700 dark:border-purple-900/30 dark:bg-purple-950/20 dark:text-purple-300">
                        Matched against <span className="font-bold">{rec.dataset_support}</span> similar dataset profiles.
                      </div>
                    ) : null}

                    {/* Stats summary */}
                    <div className="flex flex-wrap gap-4 pt-2 text-xs font-semibold text-slate-500 dark:text-slate-400">
                      <div>
                        Avg. Salary:{' '}
                        <span className="text-slate-800 dark:text-slate-200 font-bold">{rec.average_salary}</span>
                      </div>
                      <div className="hidden sm:inline-block">•</div>
                      <div>
                        Top Employers:{' '}
                        <span className="text-slate-800 dark:text-slate-200 font-bold">{rec.hiring_companies?.slice(0, 3).join(', ')}</span>
                      </div>
                    </div>
                  </div>

                  {/* Right: Score and Action shortcuts */}
                  <div className="flex flex-col items-center justify-center gap-4 border-t border-slate-50 pt-4 md:border-t-0 md:pt-0 shrink-0 md:w-48 dark:border-slate-900">
                    {/* Circle Score Gauge */}
                    <div className="relative flex h-24 w-24 items-center justify-center rounded-full bg-slate-50 dark:bg-slate-900">
                      {/* SVG Ring */}
                      <svg className="absolute top-0 left-0 h-full w-full -rotate-90">
                        <circle
                          cx="48"
                          cy="48"
                          r="42"
                          className="stroke-slate-100 dark:stroke-slate-800 fill-none"
                          strokeWidth="6"
                        />
                        <circle
                          cx="48"
                          cy="48"
                          r="42"
                          className="stroke-purple-600 fill-none"
                          strokeWidth="6"
                          strokeDasharray={2 * Math.PI * 42}
                          strokeDashoffset={2 * Math.PI * 42 * (1 - score / 100)}
                        />
                      </svg>
                      <div className="text-center z-10">
                        <span className="text-xl font-extrabold text-slate-800 dark:text-white">{score}%</span>
                        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest leading-none mt-0.5">Match</p>
                      </div>
                    </div>

                    {/* Links */}
                    <div className="flex flex-col w-full gap-2 text-center text-xs font-bold">
                      <Link 
                        to="/skill-gap" 
                        className="btn-secondary py-2 flex items-center justify-center gap-1"
                      >
                        Analyze Skill Gaps <ChevronRight className="h-3.5 w-3.5" />
                      </Link>
                      <Link 
                        to={`/careers`}
                        className="text-purple-600 hover:text-purple-700 dark:text-purple-400 py-1.5"
                      >
                        View Career Pathway
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default Recommendation;
